version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: .
    container_name: pipeline-analyzer-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pipelineDB
      - OLLAMA_URL=http://host.docker.internal:11434/api/chat
  frontend:
    build: ./frontend-react
    container_name: pipeline-analyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
volumes:
  mongo-data: