

# # services:

# #   mongodb:
# #     image: mongo
# #     ports:
# #       - "27017:27017"

# #   api:
# #     build: .
# #     container_name: pipeline-analyzer-api
# #     ports:
# #       - "5000:5000"
# #     depends_on:
# #       - mongodb
# version: "3.8"

# services:

#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"

#   api:
#     build: .
#     container_name: pipeline-analyzer-api
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_URI=mongodb://mongodb:27017/pipelineDB

version: "3.8"

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: pipeline-analyzer-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pipelineDB

volumes:
  mongo-data: